# Generated by Django 5.2.17 on 2026-08-14 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('detalle', models.TextField()),
                ('encuesta_nombre', models.CharField(blank=True, max_length=200)),
                ('encuesta_preguntas', models.CharField(blank=True, max_length=200)),
                ('duracion', models.CharField(max_length=100)),
                ('modalidad', models.CharField(max_length=100)),
                ('entregables', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('organizacion', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Asignado', 'Asignado')], default='Pendiente', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
        ),
    ]
