# Generated by Django 5.2.17 on 2026-08-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_path', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('orden', models.IntegerField(default=0)),
            ],
        ),
    ]
