# Generated by Django 5.2.17 on 2026-08-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
