# Generated by Django 5.2.17 on 2026-08-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carouselimage_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='subtitulo',
            field=models.CharField(blank=True, default='NUESTRA TRAYECTORIA & PRESENCIA', max_length=200),
        ),
    ]
