# Generated by Django 5.2.17 on 2026-08-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_systemsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('timestamp_encuesta', models.CharField(blank=True, max_length=100)),
                ('resultado', models.CharField(choices=[('Apto', 'Apto'), ('No Apto', 'No Apto')], max_length=20)),
                ('motivo', models.TextField()),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
